In [5]:
import numpy as np

In [23]:
sigmoid = lambda x : 1/(1 + np.exp(-x))
gradient = lambda gz : gz * (1 - gz)

In [28]:
def initialize(x,y):
    # Initialise x with bias
    x_nb_of_lines = x.shape[0]
    m = x_nb_of_lines
    bias = np.ones((x_nb_of_lines,1),dtype='int8')
    a1 = np.hstack([bias,x])
    
    # Initialise y
    y_unique_values_ar = np.unique(y) # find the distinct values of y
    y_class = np.zeros((x_nb_of_lines, len(y_unique_values_ar)),dtype='int8')
    for i in range(y_class.shape[0]):
        y_class[i,np.where(y_unique_values_ar == y[i])[0][0]] = 1
    
    return a1,y_class,m

In [33]:
def neural_network(x,y,theta1,theta2,sigmoid,gradient,alpha):
    #---Initialisation---#
    a1,y_class,m = initialize(x,y)
    
    #---Propagation---#
    #z2
    z2 = a1.dot(theta1)
    
    #a2
    a2 = np.vectorize(sigmoid)(z2)
    bias = np.ones((a2.shape[0],1),dtype='int8')
    a2_bias = np.hstack([bias,a2])
    
    #z3
    z3 = a2_bias.dot(theta2)
    
    #h
    h = np.vectorize(sigmoid)(z3)
    
    #---Retropropagation---#
    #delta3
    delta3 = h - y_class
    
    #delta 2
    theta2_retro = np.transpose(np.delete(theta2,0,0))
    
    ga2 = np.vectorize(gradient)(a2)
    delta2 = delta3.dot(theta2_retro) * ga2
    
    #BigDelta
    delta2_t = np.transpose(delta2)
    delta3_t = np.transpose(delta3)
    
    bigDelta2 = np.transpose(np.matmul(delta3_t,a2_bias))
    bigDelta1 = np.transpose(np.matmul(delta2_t,a1))
    
    #Weight update
    theta1_adj = theta1 - (alpha*1/m*bigDelta1)
    theta2_adj = theta2 - (alpha*1/m*bigDelta2)
    
    return theta1_adj,theta2_adj

In [54]:
x = np.array([[3,8,1],[4,2,8],[1,3,1],[3,5,4],[7,5,3],[1,5,9]])
y = np.array(['patate','patate','carrote','carrote','champignon','champignon'])
theta1 = np.array([[-0.03,0.4],[-0.01,0.05],[-0.3,0.2],[0.4,-0.8]])
theta2 = np.array([[0.2, -0.1, 0.8],[0.6,-0.6,0.2],[0.3,-0.3,0.3]])

In [56]:
theta1,theta2 = fwd_propagation(x,y,theta1,theta2,sigmoid,gradient,0.25)
print('%s \n\n %s'%(theta1,theta2))

[[-0.04305702  0.39123232]
 [-0.10124749 -0.01562256]
 [-0.37564886  0.15666005]
 [ 0.2939442  -0.82838417]] 

 [[ 0.05265717 -0.12397624  0.60933444]
 [ 0.508513   -0.59286376  0.10834025]
 [ 0.2675425  -0.33290072  0.25843345]]
